version: '3'
services:
  database:
    image: "mysql"
    container_name: tablebooker_database
    ports:
     - "3306:3306"
    environment:
     - MYSQL_ROOT_PASSWORD=changeme

  bookings:
    image: "tablebooker/bookings"
    container_name: tablebooker_bookings
    ports:
     - "4000:4000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/HealthCheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    links:
     - tablebooker_database:mysql
     
  customers:
    image: "tablebooker/customers"
    container_name: tablebooker_customers
    ports:
     - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/HealthCheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    links:
     - tablebooker_database:mysql
     
   owners:
    image: "tablebooker/owners"
    container_name: tablebooker_owners
    ports:
     - "6000:6000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000/HealthCheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    links:
     - tablebooker_database:mysql

   restaurants:
    image: "tablebooker/restaurants"
    container_name: tablebooker_restaurants
    ports:
     - "7000:7000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/HealthCheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    links:
     - tablebooker_database:mysql

   frontent:
    image: "tablebooker/frontent"
    container_name: tablebooker_frontent
    ports:
     - "8000:8000"
    links:
     - tablebooker_bookings:bookings
     - tablebooker_customers:customers
     - tablebooker_owners:owners
     - tablebooker_restaurants:restaurants
